### ISSUE TITLE
Wrap long lines in HTML

### ISSUE THREAD

**Issue by griffinlacek** [andystone40/prj-rev-bwfs-dasmoto#2]
Just a minor code styling suggestion. It's good practice to wrap long lines of code to ~80 characters so that we can see all the code in the window without scrolling. Something to keep in mind!

To wrap, just have a newline in the code itself. It won't wrap like that in the actual page since newlines in HTML are only possible through `<br />` so for most HTML you can comfortably add newlines and wrap text without changing the page look.

https://github.com/andystone40/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L12
https://github.com/andystone40/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L16
https://github.com/andystone40/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L20

**Comment by andystone40** [comment]
Thanks for this feedback!  I am using ATOM as my text editor.  I was initially annoyed with the text going off the page so I found a feature called "soft wrap" in the view menu which automatically wraps the text when you get to the end of the page but apparently it does this only for my view and does not have the same effect when I uploaded it to GitHub (or probably any other editor).  Is there a feature in ATOM that I could enable which would automatically wrap the text and save it that way even when the file is sent to a different editor?

Thanks,
Andy
